// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pahrasqqhtgbxtpesavf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhaHJhc3FxaHRnYnh0cGVzYXZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjI4NzgsImV4cCI6MjA3MjQ5ODg3OH0.BWmc-mK_Ilrdio0oYiZXm3Y7h5KVpWnMDfyWXPv_GrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});